<?php
require_once '../../config/config.php';
requireRole(['admin']);

// Get date range
$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date = $_GET['end_date'] ?? date('Y-m-t');

// Get all payments data
$payments = $db->fetchAll("
    SELECT p.*, m.member_code, u.full_name, u.email
    FROM payments p
    JOIN members m ON p.member_id = m.id
    JOIN users u ON m.user_id = u.id
    WHERE p.payment_date BETWEEN ? AND ?
    ORDER BY p.payment_date DESC
", [$start_date, $end_date]);

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="EMA_Camp_Payments_' . $start_date . '_to_' . $end_date . '.xls"');
header('Cache-Control: max-age=0');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>EMA Camp Payments Export</title>
    <style>
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        th { background-color: #1E459F; color: white; font-weight: bold; }
        .header { text-align: center; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPORAN PEMBAYARAN EMA CAMP</h1>
        <h2>Elite Martial Art Management System</h2>
        <p>Periode: <?= formatDate($start_date) ?> - <?= formatDate($end_date) ?></p>
        <p>Exported on: <?= date('d F Y H:i:s') ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Tanggal Pembayaran</th>
                <th>No. Receipt</th>
                <th>Kode Member</th>
                <th>Nama Member</th>
                <th>Email</th>
                <th>Tipe Pembayaran</th>
                <th>Metode Pembayaran</th>
                <th>Jumlah (Rp)</th>
                <th>Status</th>
                <th>Tanggal Jatuh Tempo</th>
                <th>Deskripsi</th>
            </tr>
        </thead>
        <tbody>
            <?php $no = 1; $total = 0; foreach ($payments as $payment): ?>
            <tr>
                <td><?= $no++ ?></td>
                <td><?= formatDate($payment['payment_date']) ?></td>
                <td><?= $payment['receipt_number'] ?: '-' ?></td>
                <td><?= $payment['member_code'] ?></td>
                <td><?= htmlspecialchars($payment['full_name']) ?></td>
                <td><?= htmlspecialchars($payment['email']) ?></td>
                <td><?= ucwords(str_replace('_', ' ', $payment['payment_type'])) ?></td>
                <td><?= ucwords(str_replace('_', ' ', $payment['payment_method'])) ?></td>
                <td><?= number_format($payment['amount'], 0, ',', '.') ?></td>
                <td><?= ucfirst($payment['status']) ?></td>
                <td><?= $payment['due_date'] ? formatDate($payment['due_date']) : '-' ?></td>
                <td><?= htmlspecialchars($payment['description'] ?: '-') ?></td>
            </tr>
            <?php 
            if ($payment['status'] === 'paid') $total += $payment['amount'];
            endforeach; ?>
        </tbody>
    </table>

    <div style="margin-top: 30px;">
        <table style="width: 50%; float: right;">
            <tr>
                <th>RINGKASAN</th>
                <th>NILAI</th>
            </tr>
            <tr>
                <td>Total Transaksi</td>
                <td><?= count($payments) ?></td>
            </tr>
            <tr>
                <td>Total Pembayaran Lunas</td>
                <td><?= count(array_filter($payments, function($p) { return $p['status'] === 'paid'; })) ?></td>
            </tr>
            <tr>
                <td><strong>Total Pendapatan (Rp)</strong></td>
                <td><strong><?= number_format($total, 0, ',', '.') ?></strong></td>
            </tr>
        </table>
    </div>

    <div style="clear: both; margin-top: 50px;">
        <p><strong>Generated by:</strong> <?= $_SESSION['user_name'] ?></p>
        <p><strong>Generated at:</strong> <?= date('d F Y H:i:s') ?></p>
        <p><strong>EMA Camp Management System</strong></p>
    </div>
</body>
</html>