<?php
require_once '../../config/config.php';
requireRole(['admin']);

$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date = $_GET['end_date'] ?? date('Y-m-t');

// Get trainer performance data
$trainers = $db->fetchAll("
    SELECT t.*, u.full_name,
           COUNT(DISTINCT c.id) as total_classes,
           COUNT(DISTINCT mc.member_id) as total_students,
           COALESCE(AVG(tr.rating), 0) as avg_rating,
           COUNT(tr.id) as rating_count
    FROM trainers t
    JOIN users u ON t.user_id = u.id
    LEFT JOIN classes c ON t.id = c.trainer_id AND c.is_active = 1
    LEFT JOIN member_classes mc ON c.id = mc.class_id AND mc.status = 'active'
    LEFT JOIN trainer_ratings tr ON t.id = tr.trainer_id
    WHERE u.is_active = 1
    GROUP BY t.id
    ORDER BY total_students DESC
");

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="Trainer_Performance_' . $start_date . '_to_' . $end_date . '.xls"');
header('Cache-Control: max-age=0');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Trainer Performance Report</title>
    <style>
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        th { background-color: #1E459F; color: white; font-weight: bold; }
        .header { text-align: center; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>TRAINER PERFORMANCE REPORT</h1>
        <h2>EMA Camp - Elite Martial Art</h2>
        <p>Periode: <?= formatDate($start_date) ?> - <?= formatDate($end_date) ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Trainer Code</th>
                <th>Nama Lengkap</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Spesialisasi</th>
                <th>Pengalaman (Tahun)</th>
                <th>Total Kelas</th>
                <th>Total Murid</th>
                <th>Rating</th>
                <th>Jumlah Review</th>
                <th>Tarif per Jam</th>
            </tr>
        </thead>
        <tbody>
            <?php $no = 1; foreach ($trainers as $trainer): ?>
            <tr>
                <td><?= $no++ ?></td>
                <td><?= $trainer['trainer_code'] ?></td>
                <td><?= htmlspecialchars($trainer['full_name']) ?></td>
                <td><?= htmlspecialchars($trainer['email']) ?></td>
                <td><?= htmlspecialchars($trainer['phone'] ?: '-') ?></td>
                <td><?= htmlspecialchars($trainer['specialization'] ?: '-') ?></td>
                <td><?= $trainer['experience_years'] ?></td>
                <td><?= $trainer['total_classes'] ?></td>
                <td><?= $trainer['total_students'] ?></td>
                <td><?= number_format($trainer['avg_rating'], 1) ?></td>
                <td><?= $trainer['rating_count'] ?></td>
                <td><?= $trainer['hourly_rate'] ? formatRupiah($trainer['hourly_rate']) : 'Belum diset' ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div style="margin-top: 30px;">
        <p><strong>Total Trainers:</strong> <?= count($trainers) ?></p>
        <p><strong>Generated on:</strong> <?= date('d F Y H:i:s') ?></p>
        <p><strong>Generated by:</strong> <?= $_SESSION['user_name'] ?></p>
    </div>
</body>
</html>