<?php
require_once '../../config/config.php';
requireRole(['admin', 'trainer']);

// Function to get martial art display name
function getMartialArtDisplayName($type) {
    switch($type) {
        case 'savate': return 'Savate (French Kickboxing)';
        case 'kickboxing': return 'Kickboxing';
        case 'boxing': return 'Boxing';
        default: return ucfirst($type);
    }
}

// Function to get class type display name
function getClassTypeDisplayName($type) {
    switch($type) {
        case 'regular': return 'Regular (Grup)';
        case 'private_6x': return 'Private - 6x/Bulan';
        case 'private_8x': return 'Private - 8x/Bulan';
        case 'private_10x': return 'Private - 10x/Bulan';
        default: return ucfirst($type);
    }
}

// Get all members data
$members = $db->fetchAll("
    SELECT m.*, u.full_name, u.email, u.phone, u.created_at,
           DATEDIFF(CURRENT_DATE, m.join_date) as days_joined
    FROM members m 
    JOIN users u ON m.user_id = u.id 
    WHERE u.is_active = 1
    ORDER BY u.created_at DESC
");

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="EMA_Camp_Members_' . date('Y-m-d') . '.xls"');
header('Cache-Control: max-age=0');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>EMA Camp Members Export</title>
    <style>
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        th { background-color: #1E459F; color: white; font-weight: bold; }
        .header { text-align: center; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>DAFTAR MEMBER EMA CAMP</h1>
        <h2>Elite Martial Art Management System</h2>
        <p>Exported on: <?= date('d F Y H:i:s') ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Kode Member</th>
                <th>Nama Lengkap</th>
                <th>Email</th>
                <th>Telepon</th>
                <th>Tipe Bela Diri</th>
                <th>Tipe Kelas</th>
                <th>Tanggal Bergabung</th>
                <th>Lama Bergabung (Hari)</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php $no = 1; foreach ($members as $member): ?>
            <tr>
                <td><?= $no++ ?></td>
                <td><?= $member['member_code'] ?></td>
                <td><?= htmlspecialchars($member['full_name']) ?></td>
                <td><?= htmlspecialchars($member['email']) ?></td>
                <td><?= htmlspecialchars($member['phone'] ?: '-') ?></td>
                <td><?= getMartialArtDisplayName($member['martial_art_type']) ?></td>
                <td><?= getClassTypeDisplayName($member['class_type']) ?></td>
                <td><?= formatDate($member['join_date']) ?></td>
                <td><?= $member['days_joined'] ?></td>
                <td>Aktif</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div style="margin-top: 30px;">
        <p><strong>Total Members:</strong> <?= count($members) ?></p>
        <p><strong>Generated by:</strong> <?= $_SESSION['user_name'] ?></p>
        <p><strong>Generated at:</strong> <?= date('d F Y H:i:s') ?></p>
    </div>
</body>
</html>